- name: Install Minikube
  hosts: localhost
  become: yes

  tasks:
    - name: Download Minikube .deb package
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        dest: /tmp/minikube_latest_amd64.deb

    - name: Install Minikube using dpkg
      command: dpkg -i /tmp/minikube_latest_amd64.deb

    - name: Start Minikube
      become: no
      command: minikube start
